#!/usr/bin/env bash
# build-source-map.sh — reads all segment Code: entries, builds inverse map file→segments
# Usage: build-source-map.sh <bl-dir> <output-file>
#
# Expects segment format:
#   - Code:
#     - LayerName: source/path/to/file.ts:line (construct, type: inline)
set -uo pipefail

BL_DIR="${1:?Usage: build-source-map.sh <bl-dir> <output-md>}"
OUTPUT="${2:?Usage: build-source-map.sh <bl-dir> <output-md>}"

SPLIT_DIR="$BL_DIR/split"
if [ ! -d "$SPLIT_DIR" ]; then
  echo "Error: no split/ directory in $BL_DIR" >&2
  exit 1
fi

TMPFILE=$(mktemp)
trap 'rm -f "$TMPFILE"' EXIT

normalize_path() {
  local p="$1"
  p="${p#source/}"
  p="${p#src/}"
  p="${p#./}"
  if [[ "$p" == *"/src/"* ]]; then
    p="${p#*/src/}"
  fi
  echo "$p"
}

for SEG in "$SPLIT_DIR"/*.md; do
  [ -f "$SEG" ] || continue
  SEGNAME=$(basename "$SEG")

  # Use awk to extract only entries under the - Code: section
  # Entries look like: "      - LayerName: path/file.ts:line (construct)"
  while IFS= read -r ENTRY; do
    [ -z "$ENTRY" ] && continue

    # ENTRY looks like: "path/file.ts:3-18 (construct, type: inline)"
    # Strip the trailing " (construct...)" part
    FILEPATH="${ENTRY%% (*}"
    FILEPATH=$(normalize_path "$FILEPATH")
    # Strip line numbers (e.g. ":3-18" or ":22" or ":7,50" at end of path)
    FILEPATH=$(echo "$FILEPATH" | sed -E 's/:[0-9][-0-9,]*$//')
    [ -n "$FILEPATH" ] && echo "$FILEPATH|$SEGNAME"
  done < <(awk '
    /^- Code:/ { in_code=1; next }
    /^## /     { in_code=0 }
    in_code && /^  - [A-Za-z]+: [a-zA-Z0-9_\/.-]+\.[a-zA-Z]+:[0-9]/ {
      sub(/^  - [A-Za-z]+: /, "")
      print
    }
  ' "$SEG" 2>/dev/null || true)

  # Also extract SOURCE_MAP.md format entries (generated by previous runs)
  while IFS= read -r CELL; do
    for ext in ts tsx js jsx; do
      while IFS= read -r FP; do
        [ -n "$FP" ] && echo "$(normalize_path "$FP")|$SEGNAME"
      done < <(echo "$CELL" | grep -oP "[a-zA-Z0-9_/.-]+\.$ext" 2>/dev/null || true)
    done
  done < <(grep '|.*\`.*/' "$SEG" 2>/dev/null || true)

done | sort -u > "$TMPFILE"

# Build the inverse map: file → segments
{
  echo "# Source-to-Segment Map"
  echo ""
  echo "Auto-generated by build-source-map.sh. Do not edit manually."
  echo "Generated: $(date '+%Y-%m-%d %H:%M')"
  echo ""
  echo "| Source File | Segment(s) |"
  echo "|-------------|------------|"

  CURRENT=""
  SEGS=""
  while IFS='|' read -r FILEPATH SEGNAME; do
    if [ "$FILEPATH" != "$CURRENT" ]; then
      if [ -n "$CURRENT" ]; then
        echo "| \`$CURRENT\` | $SEGS |"
      fi
      CURRENT="$FILEPATH"
      SEGS="$SEGNAME"
    else
      SEGS="$SEGS, $SEGNAME"
    fi
  done < "$TMPFILE"

  if [ -n "$CURRENT" ]; then
    echo "| \`$CURRENT\` | $SEGS |"
  fi
} > "$OUTPUT"

COUNT=$(grep -c '^| `' "$OUTPUT" || true)
echo "Source map written: $OUTPUT ($COUNT source files mapped)"
