#!/usr/bin/env bash
# rebuild-fingerprints.sh — parses all segment files and rebuilds FINGERPRINTS.md
# Usage: rebuild-fingerprints.sh <bl-dir>
# Output: overwrites FINGERPRINTS.md in <bl-dir>
set -euo pipefail

BL_DIR="${1:?Usage: rebuild-fingerprints.sh <bl-dir>}"
SPLIT_DIR="$BL_DIR/split"
OUTPUT="$BL_DIR/FINGERPRINTS.md"

if [ ! -d "$SPLIT_DIR" ]; then
  echo "Error: no split/ directory in $BL_DIR" >&2
  exit 1
fi

TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT

for SEG in "$SPLIT_DIR"/*.md; do
  [ -f "$SEG" ] || continue
  SEGNAME=$(basename "$SEG" .md)
  CONTENT=$(cat "$SEG")

  # Parse ##-format entries
  while IFS='|' read -r FP TAGS; do
    [ -n "$FP" ] && echo "$FP|$SEGNAME|$TAGS"
  done < <(echo "$CONTENT" | \
    awk '
    /^- Fingerprint: / {
      fp = substr($0, index($0, ": ") + 2)
      gsub(/^[ \t]+|[ \t]+$/, "", fp)
      if (fp != "") { f = fp; next }
    }
    /^- Tags: / && f != "" {
      tags = substr($0, index($0, ": ") + 2)
      gsub(/^[ \t]+|[ \t]+$/, "", tags)
      print f "|" tags
      f = ""
    }
    ' || true)

done | sort -u > "$TMP"

{
  echo "# Fingerprint Index"
  echo ""
  echo "Auto-generated by rebuild-fingerprints.sh. Do not edit manually."
  echo "Generated: $(date '+%Y-%m-%d %H:%M')"
  echo ""
  echo "| Fingerprint | Tags |"
  echo "|-------------|------|"

  while IFS='|' read -r FP TAGS; do
    echo "| $FP | $TAGS |"
  done < "$TMP"
} > "$OUTPUT"

COUNT=$(grep -c '^| ' "$OUTPUT" || true)
echo "OK: $OUTPUT ($COUNT fingerprint entries)"
